name: Java Tests Maven 4.0.0-rc-5

on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  maven-version: 4.0.0-rc-5

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Tests Maven 4.0.0-rc-5 with java 25

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          cache: maven
          distribution: zulu
          java-version: 25
      - name: Set Maven Wrapper version ${{ env.maven-version }}
        run: sed -i "s|^distributionUrl=.*|distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/${{ env.maven-version }}/apache-maven-${{ env.maven-version }}-bin.zip|" .mvn/wrapper/maven-wrapper.properties
      - name: Disable Maven Wrapper checksum validation
        run: sed -i '/distributionSha256Sum/d' .mvn/wrapper/maven-wrapper.properties
      - name: Test with Maven ${{ env.maven-version }}
        run: ./mvnw test --batch-mode --no-transfer-progress --show-version -Dlicense.skip=true -Dmaven=${{ env.maven-version }} -Dmaven.min-version=${{ env.maven-version }} -Dwrapper.validate=false
