name: Java Integration Tests Maven 3.6.3

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests Maven 3.6.3

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Load Maven 3.6.3
        run: mvn -B -V org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper -Dmaven=3.6.3 --no-transfer-progress
      - name: Build Setup
        run: ./mvnw -B -V clean install -Dmaven.min-version=3.6.3 -Dlicense.skip=true --no-transfer-progress
      - name: Integration Test with Maven
        run: ./mvnw -B -V -Prun-it verify -Dmaven.min-version=3.6.3 -Dlicense.skip=true --no-transfer-progress
