name: Java Integration Tests Maven 3.6.3

on: [push, pull_request]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests Maven 3.6.3

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Load Maven 3.6.3
        run: mvn -B -V org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper -Dmaven=3.6.3 --no-transfer-progress
      - name: Integration Test with Maven
        run: ./mvnw -B -V -Prun-it verify -Dmaven.min-version=3.6.3 -Dlicense.skip=true --no-transfer-progress
