name: Java Integration Tests Maven 4.0.0-beta-4

on: [push, pull_request]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests Maven 4.0.0-beta-4

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Set MVNW_VERBOSE
        run: echo "MVNW_VERBOSE=true" >> $GITHUB_ENV
      - name: Load Maven 4.0.0-beta-4
        run: mvn -B -V org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper -Dmaven=4.0.0-beta-4 --no-transfer-progress
      - name: Integration Test with Maven
        run: ./mvnw -B -V -Prun-it verify -Dmaven.min-version=4.0.0-beta-4 -Dlicense.skip=true --no-transfer-progress
